#!/bin/bash
# create-backdrop-pod.bash
#
# Author: Daniel J. R. May
#
# This script creates a pod made up of:
#
#  1. A container based on the latest official image of mariadb from
#  docker.io (docker.io/library/mariadb:latest).
#
#  2. A container based on the image generated by the
#  create-backdrop-image.bash script.
#
# For more information (or to report issues) go to
# https://github.com/danieljrmay/backdrop-pod


# Environment variables and their default values.
: "${BACKDROP_IMAGE:=backdrop-fedora}"
: "${BACKDROP_POD:=backdrop-pod}"
: "${BACKDROP_POD_PUBLISHED_PORT:=8080}"
: "${MARIADB_CONTAINER:=${BACKDROP_POD}-mariadb}"
: "${MARIADB_ROOT_PASSWORD:=mariadb-root-pwd}"
: "${MARIADB_DATABASE:=backdrop-db}"
: "${MARIADB_USER:=backdrop-db-user}"
: "${MARIADB_PASSWORD:=backdrop-db-pwd}"
: "${BACKDROP_CONTAINER:=${BACKDROP_POD}-backdrop}"


# Errors
declare -ir error_image_does_not_exist=1


# Announce that the script is running
echo "Running the create-backdrop-pod.bash script..."


# Echo the environment variables values being used by this execution
# of the script
echo "Using the following environment variables:"
echo "BACKDROP_IMAGE=$BACKDROP_IMAGE"
echo "BACKDROP_POD=$BACKDROP_POD"
echo "BACKDROP_POD_PUBLISHED_PORT=$BACKDROP_POD_PUBLISHED_PORT"
echo "MARIADB_CONTAINER=$MARIADB_CONTAINER"
echo "MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD"
echo "MARIADB_DATABASE=$MARIADB_DATABASE"
echo "MARIADB_USER=$MARIADB_USER"
echo "MARIADB_PASSWORD=$MARIADB_PASSWORD"


# Check that the backdrop image already exists.
if (podman image exists "localhost/$BACKDROP_IMAGE")
then
    echo "The localhost/$BACKDROP_IMAGE exists so we can continue..."
else   
    echo "Error: the localhost/$BACKDROP_IMAGE does not exist."
    echo "You must create this image by running the create-backdrop-image.bash script."
    exit $error_image_does_not_exist
fi


# Pull the latest version of docker.io/library/mariadb
podman pull docker.io/library/mariadb


# Create the pod
podman pod create \
       --name "$BACKDROP_POD" \
       --publish "${BACKDROP_POD_PUBLISHED_PORT}:80" \
       --network bridge


# Create the mariadb container
podman run \
       --pod "$BACKDROP_POD" \
       --name "$MARIADB_CONTAINER" \
       --env MARIADB_ROOT_PASSWORD="$MARIADB_ROOT_PASSWORD" \
       --env MARIADB_DATABASE="$MARIADB_DATABASE" \
       --env MARIADB_USER="$MARIADB_USER" \
       --env MARIADB_PASSWORD="$MARIADB_PASSWORD" \
       --detach \
       docker.io/library/mariadb:latest


# Create the backdrop container
podman run \
       --pod "$BACKDROP_POD" \
       --name "$BACKDROP_CONTAINER" \
       --env BACKDROP_DATABASE_NAME="$MARIADB_DATABASE" \
       --env BACKDROP_DATABASE_USER="$MARIADB_USER" \
       --env BACKDROP_DATABASE_PASSWORD="$MARIADB_PASSWORD" \
       --detach \
       localhost/$BACKDROP_IMAGE


# Announce finish with instructions to complete backdrop installation
# via browser
echo 'Finished. Please continue the backdrop installation by visiting http://localhost:8080/core/install.php'
